#!/bin/bash

cgroup_path="/sys/fs/cgroup/memory/cgroup1"
cgroup_memory_limit="256M"
mkdir ${cgroup_path}
pushd ${cgroup_path}
echo "${cgroup_memory_limit}" > memory.limit_in_bytes
echo $$ > tasks
popd

memory_limit="128M"

stress --quiet --vm 4 --vm-bytes ${memory_limit} --vm-keep &>/dev/null &
trap 'kill -9 $(pgrep -P '$!') &> /dev/null; cgdelete memory:/cgroup1' EXIT
while true; do
    total=0;
    for p in $(pgrep -P $!); do
        rss=$(grep "^VmRSS" "/proc/$p/status" | awk '{print $2}');
        process=$(ps -q ${p} -eo ppid,pid,cgroup | grep ${p} | awk -F , '{print $1}')
        total=$(($total + $rss));
        echo "$process ==> $(($rss/1024))MB"
    done;
    echo "Total ==> $(($total/1024))MB";
done
