#!/bin/bash

set -x
# Number of workers
workers=2
# Memory per worker
memory_limit="2048M"

stress --quiet --vm 2 --vm-bytes ${memory_limit} --vm-keep &>/dev/null &
trap 'kill -9 $(pgrep -P '$!') &> /dev/null' EXIT
while true; do
    total=0;
    pgrep -P $!
    for p in $(pgrep -P $!); do
        rss=$(grep "^VmRSS" "/proc/$p/status" | awk '{print $2}');
        total=$(($total + $rss));
    done;
    echo "$(($total/1000)) MB";
done
